language: node_js

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c mocha.conf --only=tests --test-run-id=177999

script:
  - mocha test


after_script:
  - hiptest-publisher -c mocha.conf --push="results.xml" --test-run-id=177999
